config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy # @restaurant.reviews 가능

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian) }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, presence: true, :inclusion => 0..5, numericality: { only_integer: true }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
   before_action :find_param, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path(@restaurant)
    else
      render :new
    end
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def edit
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.required(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def find_param
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between">
    <span class="navbar-brand"><%= link_to "Restaurant",  restaurants_path  %></span>
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><%= link_to "add restaurant",  new_restaurant_path  %></button>
  </nav>
  <div class ="main-content">
    <%= yield %>
  </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, :collection => ["chinese", "italian", "japanese", "french", "belgian"]%>
  <%= f.submit "Add a restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/edit.html.erb
<h1> Edit < <%= @restaurant.name %> > information</h1>
<%= render 'form' %>

app/views/restaurants/index.html.erb
<% @restaurants.each do |restaurant| %>
<div class="mt-4">
<ul>
<li><%= link_to restaurant.name, restaurant_path(restaurant)%></li>
</ul>
</div>

<% end %>

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1>Restaurant information</h1>

<div>
<hr>
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @restaurant.phone_number %>
</p>

<p>
  <strong>Category:</strong>
  <%= @restaurant.category %>
</p>

<h3>Reviews</h3>
<hr>
<% @restaurant.reviews.each do |review| %>
  <span>Rating: <%= '⭐️'* review.rating %>  <br></span>
  <span>Content: <%= review.content %> <br></span>
  <hr>
<% end  %>


</div>

<button class = "btn btn-dark"><%= link_to "Back", restaurants_path %></button>
<button class = "btn btn-dark"><%= link_to "Edit", edit_restaurant_path(@restaurant) %></button>
<button class = "btn btn-dark"><%= link_to "Delete", restaurant_path(@restaurant), method: :delete, data: { confirm: "Are you sure?" } %></button>
<button class = "btn btn-dark"><%= link_to "Write review", new_restaurant_review_path(@restaurant) %></button>

app/views/reviews/new.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :rating, :collection => 1..5, :prompt => "Select rating" %>
  <%= f.input :content %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>